### PR TITLE
Add gestures

### LINKED ISSUE #78: More refined home screen gestures
Received from Veloci Raptor via mail:

### General Information

  * Essential Launcher Version: 2.2
  
### Actual behavior

Right now, "any" gesture on the home screen launches the app drawer, and it kinda doesn't feel right.

### Expected behavior

Here's what i'd like to see:
Swipe up - Open drawer
Swipe down - Open Notifications
Tap/Right Swipe/Left Swipe - Nothing

### PR DESCRIPTION
**Pull request by c6p**
Fixes #78.

I have modified `ViewController`. Added an easily extendable `Gestures` `enum` for keys (swipeUp, swipeDown) and default values (drawer, notifications) of gestures.

`onLongPress` always launches app drawer to be able to edit settings.

Added `SHOW_STATUSBAR_ID, SHOW_DRAWER_ID, SHOW_SEARCH_ID ` for target pages and `showGestureTarget` to show them.

Swipe up/down items in action bar menu are used to assign new targets. 

(Sorry for the commit mess, I guess I need to sleep)

### CODE REVIEW

**Comment by clemensbartz** [comment]
Thank you very much for your contribution! I will need a little time until I can take a look at this one. I think the upcoming weekend is possible. I will also check the codebeat report then. 

@c6p Could you run the connectedAndroidTest Gradle goal locally please, to see if the Android Tests are working correctly? This does not run automatically in Travis.

**Comment by c6p** [comment]
@clemensbartz tests did not run. It is not running on unmodified repo too. It could be my setup, I will try again tomorrow.

**Comment by clemensbartz** [comment]
@c6p So sorry for wasting your time with this. The correct goal is called `connectedCheck` in module `launcher`. Please make sure to have at least one emulator open. If you could, running this on a tablet in landscape mode as well would be much appreciated.

**Comment by c6p** [comment]
Ok. @clemensbartz both (origin and my fork) fail 4 out of 9 tests on Android 10 emulator. I will look into why/where, try with different versions.

**Comment by clemensbartz** [comment]
I will take a look also from the original perspective on the weekend.

**Comment by clemensbartz** [comment]
So indeed, my commits have introduced some issues. I will do two things here:

1. Set up Travis to do some checking at least on one Android version in order to avoid this in the future.
2. Fix the issues. When this is done, we can rebase on this pull request and continue the discussion here.

I will also merge the Turkish translation pull request in the meantime.

**Comment by clemensbartz** [comment]
I found the issues with the failing tests. I am currently trying all day to get Travis to consistently execute tests. Will let you know once this is done.

**Comment by clemensbartz** [comment]
Alright. I ditched Travis CI and went for GitHub Actions (after numerous attempts). So now we have a fully integrated chain. Would you please be so kind to rebase this pull request to the latest master and check again?

**Comment by c6p** [comment]
Thanks for merging Turkish translation. Sorry I was away. I am going to rebase tomorrow.

**Comment by c6p** [comment]
Sorry, a bit late. Ok, it is done. `connectedCheck` is passing.

**Comment by clemensbartz** [comment]
Cherry-picked commit 7a3d6d1d30c267e7a0d28955c980b55a22a8c114 into release/v2.3.

**Comment by clemensbartz** [comment]
@c6p I just wanted to express my gratitude again for implementing this feature. It looks really slick! 

There still needs to be some UI tests for it (I raised issue #86), before I can put it in production. But I need to include SonarQube first before any of that makes sense.

**Pull request closed without merging**
